version: '3'
services:
  mysql:
    container_name: prestashop-mysql
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    platform: linux/x86_64
    ports:
      - 19966:80
    environment:
      DB_SERVER: prestashop-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_DOMAIN: localhost:19966
    networks:
      - prestashop_network
networks:
  prestashop_network:
